name: Flask CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM and restart Flask
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            # Navigate to app directory
            cd /home/manisha/flask-ci-cd-app

            # Pull latest code
            git pull origin main

            # Install/update dependencies
            source /home/manisha/venv/bin/activate
            pip install -r requirements.txt

            # Restart Flask service (systemd handles venv)
            sudo systemctl restart flask-app.service
            sudo systemctl status flask-app.service --no-pager
