name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          port: ${{ secrets.VM_PORT }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd /home/manisha/flask-ci-cd-app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f "python app.py" || true
            nohup python app.py > app.log 2>&1 &
