name: Flask CI/CD Pipeline (Password SSH)

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Add your test commands here"
          # Example: python -m unittest discover tests

  deploy:
    name: Deploy to VM
    runs-on: [self-hosted, Linux, X64]
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VM and start Flask
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            cd /home/manisha/flask-ci-cd-app
            git pull origin main
            source /home/manisha/venv/bin/activate
            pip install -r requirements.txt
            pkill -f "python3 app.py" || true
            nohup python app.py > app.log 2>&1 &
