services:
  web:
    build: .
    container_name: flask-ci-cd-app-flaskapp
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: flask-ci-cd-app-mongo
